language: python
python:
    - '3.7'
install:
    - pip install -r requirements.txt
script:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then pytest tests/test_prod; fi
    - if [ "$TRAVIS_BRANCH" = "development" ]; then pytest tests/test_dev; fi
